package io.synadia.authcallout.server;

import org.bouncycastle.crypto.macs.Poly1305;
import org.bouncycastle.crypto.params.KeyParameter;
import org.bouncycastle.crypto.params.X25519PrivateKeyParameters;
import org.bouncycastle.crypto.params.X25519PublicKeyParameters;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Verifies CurveKeyHelper.open() against a known NaCl box test vector
 * generated by Python's cryptography library (which uses libsodium).
 *
 * Test vector parameters:
 *   recv_priv_raw  = bytes 0x01..0x20
 *   sender_pub_raw = 5869aff450549732cbaaed5e5df9b30a6da31cb0e5742bad5ad4a1a768f1a67b
 *   nonce          = bytes 0x00..0x17 (24 bytes)
 *   plaintext      = "hello world"
 *   payload        = nonce(24) | mac(16) | ciphertext
 */
class CurveKeyHelperTest {

    // Standard NKey base32 alphabet
    private static final String BASE32 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";

    // NKey prefix byte for curve25519 public keys: 23 << 3 = 0xB8
    private static final int PREFIX_CURVE_PUB = 23 << 3;

    /** Encode raw curve25519 public key bytes as an NKey public key string. */
    private static String encodeXKeyNKey(byte[] rawPub) {
        byte[] full = new byte[35]; // 1 prefix + 32 key + 2 CRC
        full[0] = (byte) PREFIX_CURVE_PUB;
        System.arraycopy(rawPub, 0, full, 1, 32);
        int crc = crc16(full, 33);
        full[33] = (byte) (crc & 0xFF);       // little-endian
        full[34] = (byte) (crc >> 8);
        return base32Encode(full);
    }

    /** Encode raw curve25519 seed bytes as an NKey seed string (SX...). */
    private static String encodeXKeySeed(byte[] rawPriv) {
        // Seed: 2 prefix bytes | 32 key | 2 CRC = 36 bytes
        byte[] full = new byte[36];
        // Seed prefix1 = (18 << 3) | (23 >> 5) = 144 | 0 = 0x90
        // Seed prefix2 = (23 & 0x1F) << 3       = 23 << 3 = 0xB8... actually:
        // In nkeys: seedPrefix = PrefixByteSeed (18<<3=144) | (type >> 5)
        //           second byte = (type & 0x1F) << 3
        // For curve (23): prefix1 = 144 | (23>>5) = 144 | 0 = 144; prefix2 = (23&31)<<3 = 23<<3 = 184
        full[0] = (byte) 144; // PrefixByteSeed | (CURVE >> 5)
        full[1] = (byte) 184; // (CURVE & 0x1F) << 3
        System.arraycopy(rawPriv, 0, full, 2, 32);
        int crc = crc16(full, 34);
        full[34] = (byte) (crc & 0xFF);
        full[35] = (byte) (crc >> 8);
        return base32Encode(full);
    }

    private static int crc16(byte[] data, int length) {
        int crc = 0;
        for (int i = 0; i < length; i++) {
            crc ^= (data[i] & 0xFF) << 8;
            for (int j = 0; j < 8; j++) {
                crc = (crc & 0x8000) != 0 ? (crc << 1) ^ 0x1021 : crc << 1;
            }
        }
        return crc & 0xFFFF;
    }

    private static String base32Encode(byte[] data) {
        StringBuilder sb = new StringBuilder();
        int bits = 0, value = 0;
        for (byte b : data) {
            value = (value << 8) | (b & 0xFF);
            bits += 8;
            while (bits >= 5) {
                sb.append(BASE32.charAt((value >> (bits - 5)) & 0x1F));
                bits -= 5;
            }
        }
        if (bits > 0) sb.append(BASE32.charAt((value << (5 - bits)) & 0x1F));
        return sb.toString();
    }

    private static byte[] fromHex(String hex) {
        int len = hex.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(hex.charAt(i), 16) << 4)
                                 + Character.digit(hex.charAt(i + 1), 16));
        }
        return data;
    }

    // ── NaCl secretbox seal (for test vector generation) ─────────────────────

    /**
     * Encrypts plaintext using the standard NaCl secretbox (XSalsa20-Poly1305) format,
     * matching Go's nacl/box.Seal output:
     *   "xkv1"(4) | nonce(24) | MAC(16) | ciphertext
     *
     * Keystream layout:
     *   block0[0..31]  = Poly1305 key
     *   block0[32..63] = keystream for plaintext[0..31]
     *   block1[0..63]  = keystream for plaintext[32..95], etc.
     */
    private static byte[] sealNaCl(byte[] senderPrivRaw, byte[] recvPubRaw,
                                   byte[] nonce24, byte[] plaintext) throws Exception {
        // DH
        X25519PrivateKeyParameters senderPriv = new X25519PrivateKeyParameters(senderPrivRaw);
        X25519PublicKeyParameters  recvPub    = new X25519PublicKeyParameters(recvPubRaw);
        byte[] rawDh = new byte[32];
        senderPriv.generateSecret(recvPub, rawDh, 0);

        // box.Precompute: HSalsa20(rawDH, zeros)
        byte[] boxKey = hSalsa20(rawDh, new byte[16]);

        // XSalsa20 subkey derivation
        byte[] subKey     = hSalsa20(boxKey, Arrays.copyOfRange(nonce24, 0, 16));
        byte[] innerNonce = Arrays.copyOfRange(nonce24, 16, 24);

        // Keystream
        byte[] block0 = salsa20Block(subKey, innerNonce, 0);
        byte[] polyKey = Arrays.copyOfRange(block0, 0, 32);

        // Encrypt: block0[32..63] then block1, block2, ...
        byte[] ciphertext = new byte[plaintext.length];
        int pos = 0;
        int firstChunk = Math.min(32, plaintext.length);
        for (int i = 0; i < firstChunk; i++) ciphertext[i] = (byte)(plaintext[i] ^ block0[32 + i]);
        pos = firstChunk;
        for (int blockNum = 1; pos < plaintext.length; blockNum++) {
            byte[] ks = salsa20Block(subKey, innerNonce, blockNum);
            int n = Math.min(64, plaintext.length - pos);
            for (int i = 0; i < n; i++) ciphertext[pos + i] = (byte)(plaintext[pos + i] ^ ks[i]);
            pos += n;
        }

        // MAC = Poly1305(polyKey, ciphertext)
        Poly1305 mac = new Poly1305();
        mac.init(new KeyParameter(polyKey));
        mac.update(ciphertext, 0, ciphertext.length);
        byte[] tag = new byte[16];
        mac.doFinal(tag, 0);

        // Assemble: "xkv1" | nonce(24) | MAC(16) | ciphertext
        byte[] out = new byte[4 + 24 + 16 + ciphertext.length];
        out[0]='x'; out[1]='k'; out[2]='v'; out[3]='1';
        System.arraycopy(nonce24,    0, out,  4, 24);
        System.arraycopy(tag,        0, out, 28, 16);
        System.arraycopy(ciphertext, 0, out, 44, ciphertext.length);
        return out;
    }

    // ── Salsa20 helpers (mirrors CurveKeyHelper private methods) ─────────────

    private static byte[] salsa20Block(byte[] key, byte[] nonce8, int counter) {
        int[] s = new int[16];
        s[0]=0x61707865; s[1]=le32(key,0);  s[2]=le32(key,4);  s[3]=le32(key,8);  s[4]=le32(key,12);
        s[5]=0x3320646e; s[6]=le32(nonce8,0); s[7]=le32(nonce8,4); s[8]=counter; s[9]=0;
        s[10]=0x79622d32; s[11]=le32(key,16); s[12]=le32(key,20); s[13]=le32(key,24); s[14]=le32(key,28);
        s[15]=0x6b206574;
        int[] x = s.clone();
        for (int i = 0; i < 10; i++) {
            qr(x,0,4,8,12); qr(x,5,9,13,1); qr(x,10,14,2,6); qr(x,15,3,7,11);
            qr(x,0,1,2,3);  qr(x,5,6,7,4);  qr(x,10,11,8,9); qr(x,15,12,13,14);
        }
        byte[] out = new byte[64];
        for (int i = 0; i < 16; i++) le32b(x[i]+s[i], out, i*4);
        return out;
    }

    private static byte[] hSalsa20(byte[] key, byte[] in16) {
        int[] x = new int[16];
        x[0]=0x61707865; x[1]=le32(key,0); x[2]=le32(key,4); x[3]=le32(key,8); x[4]=le32(key,12);
        x[5]=0x3320646e; x[6]=le32(in16,0); x[7]=le32(in16,4); x[8]=le32(in16,8); x[9]=le32(in16,12);
        x[10]=0x79622d32; x[11]=le32(key,16); x[12]=le32(key,20); x[13]=le32(key,24); x[14]=le32(key,28);
        x[15]=0x6b206574;
        for (int i = 0; i < 10; i++) {
            qr(x,0,4,8,12); qr(x,5,9,13,1); qr(x,10,14,2,6); qr(x,15,3,7,11);
            qr(x,0,1,2,3);  qr(x,5,6,7,4);  qr(x,10,11,8,9); qr(x,15,12,13,14);
        }
        byte[] out = new byte[32];
        le32b(x[0],out,0); le32b(x[5],out,4); le32b(x[10],out,8); le32b(x[15],out,12);
        le32b(x[6],out,16); le32b(x[7],out,20); le32b(x[8],out,24); le32b(x[9],out,28);
        return out;
    }

    private static void qr(int[] x, int a, int b, int c, int d) {
        x[b]^=rotl(x[a]+x[d],7); x[c]^=rotl(x[b]+x[a],9);
        x[d]^=rotl(x[c]+x[b],13); x[a]^=rotl(x[d]+x[c],18);
    }
    private static int rotl(int v, int n) { return (v<<n)|(v>>>(32-n)); }
    private static int le32(byte[] b, int o) {
        return (b[o]&0xFF)|((b[o+1]&0xFF)<<8)|((b[o+2]&0xFF)<<16)|((b[o+3]&0xFF)<<24);
    }
    private static void le32b(int v, byte[] b, int o) {
        b[o]=(byte)v; b[o+1]=(byte)(v>>8); b[o+2]=(byte)(v>>16); b[o+3]=(byte)(v>>24);
    }

    @Test
    void testOpenWithNaClBoxFormat() throws Exception {
        // Receiver private key (raw 32 bytes: 0x01..0x20)
        byte[] recvPrivRaw = new byte[32];
        for (int i = 0; i < 32; i++) recvPrivRaw[i] = (byte)(i + 1);

        // Sender ephemeral private key (raw 32 bytes: 0x21..0x40)
        byte[] senderPrivRaw = new byte[32];
        for (int i = 0; i < 32; i++) senderPrivRaw[i] = (byte)(i + 0x21);

        // Derive sender's public key
        X25519PrivateKeyParameters senderPrivParams = new X25519PrivateKeyParameters(senderPrivRaw);
        byte[] senderPubRaw = senderPrivParams.generatePublicKey().getEncoded();

        // Derive receiver's public key (needed for sender's DH)
        X25519PrivateKeyParameters recvPrivParams = new X25519PrivateKeyParameters(recvPrivRaw);
        byte[] recvPubRaw = recvPrivParams.generatePublicKey().getEncoded();

        // Nonce: bytes 0x00..0x17
        byte[] nonce24 = new byte[24];
        for (int i = 0; i < 24; i++) nonce24[i] = (byte)i;

        // Seal using correct NaCl secretbox format
        byte[] plaintext = "hello world".getBytes();
        byte[] payload   = sealNaCl(senderPrivRaw, recvPubRaw, nonce24, plaintext);

        // Encode keys as NKey strings
        String seedNKey   = encodeXKeySeed(recvPrivRaw);
        String senderNKey = encodeXKeyNKey(senderPubRaw);

        System.out.println("Seed NKey:   " + seedNKey);
        System.out.println("Sender NKey: " + senderNKey);

        // Decrypt and verify
        CurveKeyHelper helper = new CurveKeyHelper(seedNKey);
        byte[] result = helper.open(payload, senderNKey);

        assertNotNull(result, "Decryption failed (MAC mismatch or corrupted payload)");
        assertEquals("hello world", new String(result));
    }
}
