# Operator named AuthCalloutOperator
operator: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJGSVFWS1AzUVMzRjJHVU9XSTc3STdBNTZQQ0JKUkFQTjQ1M0RVSjJFR0RLS0E2QkRNQ1BBIiwiaWF0IjoxNzc3NDgzMzI1LCJpc3MiOiJPQ0NSMzRBSUU3Vk5TNEhQWjRUMk1ZQ1JYVE82WVBMQVdORUpJVFdHTTRUU1UzUDUzR1dCSkpESSIsIm5hbWUiOiJBdXRoQ2FsbG91dE9wZXJhdG9yIiwic3ViIjoiT0NDUjM0QUlFN1ZOUzRIUFo0VDJNWUNSWFRPNllQTEFXTkVKSVRXR000VFNVM1A1M0dXQkpKREkiLCJuYXRzIjp7ImFjY291bnRfc2VydmVyX3VybCI6Im5hdHM6Ly9sb2NhbGhvc3Q6NDIyMiIsInN5c3RlbV9hY2NvdW50IjoiQUJPSERNSlBON0xKRjZJSFlaWkZFQlQ3VEhXTEM3VVZEWEozQjRJMlEyUVZSQkNMTE5ITFMzWDUiLCJ0eXBlIjoib3BlcmF0b3IiLCJ2ZXJzaW9uIjoyfX0._YupuUDpoSnRMq1loD8mEV1vDe15-bCtx9YAeJxztW7QC4SsCOX-8Oig2X71bjhC8XpH8uJS2WccrUs79I7HBQ
# System Account named SYS
system_account: ABOHDMJPN7LJF6IHYZZFEBT7THWLC7UVDXJ3B4I2Q2QVRBCLLNHLS3X5

# configuration of the nats based resolver
resolver {
    type: full
    # Directory in which the account jwt will be stored
    dir: './jwt'
    # In order to support jwt deletion, set to true
    # If the resolver type is full delete will rename the jwt.
    # This is to allow manual restoration in case of inadvertent deletion.
    # To restore a jwt, remove the added suffix .delete and restart or send a reload signal.
    # To free up storage you must manually delete files with the suffix .delete.
    allow_delete: false
    # Interval at which a nats-server with a nats based account resolver will compare
    # it's state with one random nats based account resolver in the cluster and if needed, 
    # exchange jwt and converge on the same set of jwt.
    interval: "2m"
    # Timeout for lookup requests in case an account does not exist locally.
    timeout: "1.9s"
}


# Preload the nats based resolver with the system account jwt.
# This is not necessary but avoids a bootstrapping system account. 
# This only applies to the system account. Therefore other account jwt are not included here.
# To populate the resolver:
# 1) make sure that your operator has the account server URL pointing at your nats servers.
#    The url must start with: "nats://" 
#    nsc edit operator --account-jwt-server-url nats://localhost:4222
# 2) push your accounts using: nsc push --all
#    The argument to push -u is optional if your account server url is set as described.
# 3) to prune accounts use: nsc push --prune 
#    In order to enable prune you must set above allow_delete to true
# Later changes to the system account take precedence over the system account jwt listed here.
resolver_preload: {
	ABOHDMJPN7LJF6IHYZZFEBT7THWLC7UVDXJ3B4I2Q2QVRBCLLNHLS3X5: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJDQUI3S0FJMkpSWURKSkxLTVhSVE1aVkJJWU5TVVFPR0NBTlI1RVoyWkRKRjRRQzNHNEpRIiwiaWF0IjoxNzc3NDgzMjcwLCJpc3MiOiJPQ0NSMzRBSUU3Vk5TNEhQWjRUMk1ZQ1JYVE82WVBMQVdORUpJVFdHTTRUU1UzUDUzR1dCSkpESSIsIm5hbWUiOiJTWVMiLCJzdWIiOiJBQk9IRE1KUE43TEpGNklIWVpaRkVCVDdUSFdMQzdVVkRYSjNCNEkyUTJRVlJCQ0xMTkhMUzNYNSIsIm5hdHMiOnsibGltaXRzIjp7InN1YnMiOi0xLCJkYXRhIjotMSwicGF5bG9hZCI6LTEsImltcG9ydHMiOi0xLCJleHBvcnRzIjotMSwid2lsZGNhcmRzIjp0cnVlLCJjb25uIjotMSwibGVhZiI6LTF9LCJkZWZhdWx0X3Blcm1pc3Npb25zIjp7InB1YiI6e30sInN1YiI6e319LCJhdXRob3JpemF0aW9uIjp7fSwidHlwZSI6ImFjY291bnQiLCJ2ZXJzaW9uIjoyfX0.PS-5JX-o_YOcuc2kIFerBaAZ6RVjpuva2fcXRfhusgAVNOlM8ntu8bqnLaYRGESKuC1VXp3vP-WT1rvul7LqAA,
}


