accounts {
  SYS: {
    users: [ 
      { user: sys, password: sys }
    ]
  }
  AUTH: {
    jetstream: true
    users: [ 
      #{ user: auth, password: auth, permissions: { subscribe: ["$SYS.REQ.USER.AUTH", "$SRV.>"], allow_responses: true } 
      { user: auth, password: auth } 
      { user: john, password: john }
  
    ]
  }
  APP: {
    jetstream: true
  }
  APP1: {
    jetstream: true
  }
  APP2: {
    jetstream: true
    
  }
}