include accounts.conf



jetstream {
  domain: "MY_DOMAIN"
  #store_dir: "/app"
}

authorization {
  auth_callout {
    account: AUTH
    issuer: AB5Z5IIYMIGSGE2EBGRDKQM4L3EORUDBYKILWLJLVN4VJCGJANGIXX7M
    users: [ auth, sys]
    #xkey: XC3Y4IUMK5JSG4476OHCKG3LZMVCZ4LOKXWTDYB56D5HW6EJHJABZKX6
  }
}

system_account: SYS
